include:
  - gateway.bash
  - gateway.git
  - gateway.etckeeper
  - gateway.mosh
  - gateway.tmp
  - gateway.ntp
  - gateway.network
  - gateway.batman
  - gateway.fastd
  - gateway.alfred
  - gateway.name-server
  - gateway.fail2ban
  - gateway.apache
  - gateway.syslog
  - map.rrd
  - map.ffmap-backend
  - map.meshviewer
