#!/bin/sh
#
#

### BEGIN INIT INFO
# Provides:          alfred
# Required-Start:    $remote_fs $network $syslog
# Required-Stop:     $remote_fs $network $syslog
# Should-Start:      $local_fs slapd $named
# Should-Stop:       $local_fs slapd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: A.L.F.R.E.D.
# Description:       A.L.F.R.E.D. Almighty Lightweight Fact Remote Exchange Daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

test -f /usr/sbin/alfred || exit 0

ALFRED_DEFAULT="${ALFRED_DEFAULT:-/etc/default/alfred}"

# It is not safe to start if we don't have a default configuration...
if [ ! -f "$ALFRED_DEFAULT" ]; then
        echo "$ALFRED_DEFAULT does not exist! - Aborting..."
        if [ "$ALFRED_DEFAULT" = "/etc/default/alfred" ]; then
                echo "Run 'salt' to fix the problem."
        fi
        exit 0
fi

. /lib/lsb/init-functions

# Read init script configuration
[ -f "$ALFRED_DEFAULT" ] && . "$ALFRED_DEFAULT"

NAME=alfred
DESC="A.L.F.R.E.D. Almighty Lightweight Fact Remote Exchange Daemon"
ALFRED_PID="${ALFRED_PID:-/var/run/alfred.pid}"

# single arg is -v for messages, -q for none
check_status()
{
    if [ ! -r "$ALFRED_PID" ]; then
        test "$1" != -v || echo "$NAME is not running."
        return 3
    fi
    if read pid < "$ALFRED_PID" && ps -p "$pid" > /dev/null 2>&1; then
        test "$1" != -v || echo "$NAME is running."
        return 0
    else
        test "$1" != -v || echo "$NAME is not running but $ALFRED_PID exists."
        return 1
    fi
}

case "$1" in
        start)
                test_config
                if [ -e "$ALFRED_PID" ]; then
                        log_failure_msg "alfred service already running (pid file $ALFRED_PID currenty exists)"
                        exit 1
                fi
                log_daemon_msg "Starting $DESC" "$NAME"
                start-stop-daemon --start --quiet --pidfile "$ALFRED_PID" \
                        --exec /usr/bin/alfred -i $INTERFACE -b $BATMANIF
                sleep 2

                if check_status -q; then
                        log_end_msg 0
                else
                        log_failure_msg "check syslog for diagnostics."
                        log_end_msg 1
                        exit 1
                fi
                ;;
        stop)
                log_daemon_msg "Stopping $DESC" "$NAME"
                start-stop-daemon --stop --quiet --pidfile "$ALFRED_PID"
                log_end_msg $?
                rm -f "$ALFRED_PID"
                ;;
        restart | force-reload)
                test_config
                $0 stop
                sleep 2
                $0 start
                if [ "$?" != "0" ]; then
                        exit 1
                fi
                ;;
        status)
                echo -n "Status of $DESC: "
                check_status -v
                exit "$?"
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|force-reload|status}"
                exit 1
esac

exit 0
