#!/bin/sh
#
#

### BEGIN INIT INFO
# Provides:          batadv-vis
# Required-Start:    $remote_fs $network $syslog
# Required-Stop:     $remote_fs $network $syslog
# Should-Start:      $local_fs slapd $named
# Should-Stop:       $local_fs slapd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: batadv-vis
# Description:       batadv-vis Visualization Server
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

test -f /usr/sbin/batadv-vis || exit 0

BATADV_VIS_DEFAULT="${BATADV_VIS_DEFAULT:-/etc/default/batadv-vis}"

# It is not safe to start if we don't have a default configuration...
if [ ! -f "$BATADV_VIS_DEFAULT" ]; then
        echo "$BATADV_VIS_DEFAULT does not exist! - Aborting..."
        if [ "$BATADV_VIS_DEFAULT" = "/etc/default/alfred" ]; then
                echo "Run 'salt' to fix the problem."
        fi
        exit 0
fi

. /lib/lsb/init-functions

# Read init script configuration
[ -f "$BATADV_VIS_DEFAULT" ] && . "$BATADV_VIS_DEFAULT"

NAME=batadv-vis
DESC="batadv-vis Visualization Server"
BATADV_VIS_PID="${BATADV_VIS_PID:-/var/run/dhcpd6.pid}"

# single arg is -v for messages, -q for none
check_status()
{
    if [ ! -r "$BATADV_VIS_PID" ]; then
        test "$1" != -v || echo "$NAME is not running."
        return 3
    fi
    if read pid < "$BATADV_VIS_PID" && ps -p "$pid" > /dev/null 2>&1; then
        test "$1" != -v || echo "$NAME is running."
        return 0
    else
        test "$1" != -v || echo "$NAME is not running but $BATADV_VIS_PID exists."
        return 1
    fi
}

case "$1" in
        start)
                test_config
                if [ -e "$BATADV_VIS_PID" ]; then
                        log_failure_msg "batadv-vis service already running (pid file $BATADV_VIS_PID currenty exists)"
                        exit 1
                fi
                log_daemon_msg "Starting $DESC" "$NAME"
                start-stop-daemon --start --quiet --pidfile "$BATADV_VIS_PID" \
                        --exec /usr/bin/batadv-vis -s -i $INTERFACE
                sleep 2

                if check_status -q; then
                        log_end_msg 0
                else
                        log_failure_msg "check syslog for diagnostics."
                        log_end_msg 1
                        exit 1
                fi
                ;;
        stop)
                log_daemon_msg "Stopping $DESC" "$NAME"
                start-stop-daemon --stop --quiet --pidfile "$BATADV_VIS_PID"
                log_end_msg $?
                rm -f "$BATADV_VIS_PID"
                ;;
        restart | force-reload)
                test_config
                $0 stop
                sleep 2
                $0 start
                if [ "$?" != "0" ]; then
                        exit 1
                fi
                ;;
        status)
                echo -n "Status of $DESC: "
                check_status -v
                exit "$?"
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|force-reload|status}"
                exit 1
esac

exit 0
